import { Pawn } from './pawn';

export const PAWNS: Pawn[] = [
  { piece: 'r', name: 'Tower', color: 'white', xPos: 0, yPos: 0},
  { piece: 'h', name: 'Horse', color: 'white', xPos: 0, yPos: 1},
  { piece: 'b', name: 'Officer', color: 'white', xPos: 0, yPos: 2},
  { piece: 'q', name: 'Queen', color: 'white', xPos: 0, yPos: 3},
  { piece: 'k', name: 'King', color: 'white', xPos: 0, yPos: 4},
  { piece: 'b', name: 'Officer', color: 'white', xPos: 0, yPos: 5},
  { piece: 'h', name: 'Horse', color: 'white', xPos: 0, yPos: 6},
  { piece: 'r', name: 'Tower', color: 'white', xPos: 0, yPos: 7},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 0},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 1},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 2},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 3},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 4},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 5},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 6},
  { piece: 'p', name: 'Soldier', color: 'white', xPos: 1, yPos: 7},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 0},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 1},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 2},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 3},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 4},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 5},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 6},
  { piece: 'o', name: 'Soldier', color: 'black', xPos: 6, yPos: 7},
  { piece: 't', name: 'Tower', color: 'black', xPos: 7, yPos: 0},
  { piece: 'j', name: 'Horse', color: 'black', xPos: 7, yPos: 1},
  { piece: 'n', name: 'Officer', color: 'black', xPos: 7, yPos: 2},
  { piece: 'w', name: 'Queen', color: 'black', xPos: 7, yPos: 3},
  { piece: 'l', name: 'King', color: 'black', xPos: 7, yPos: 4},
  { piece: 'n', name: 'Officer', color: 'black', xPos: 7, yPos: 5},
  { piece: 'j', name: 'Horse', color: 'black', xPos: 7, yPos: 6},
  { piece: 't', name: 'Tower', color: 'black', xPos: 7, yPos: 7},
];

